import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/components/navigation/Navigation";
import "./globals.css";
import { FC, ReactNode } from "react";

type RootLayoutProps = {
  children: ReactNode;
};

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
